# Generated by Django 4.1 on 2023-04-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_usuarios_partidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidas',
            name='id_ususario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='game.usuarios'),
        ),
    ]
