# Generated by Django 4.1 on 2023-04-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_partidas_id_ususario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidas',
            old_name='id_ususario',
            new_name='id_usuario',
        ),
    ]
